ifx/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import register_converter
from django.views.generic import RedirectView

from ifx.converters import IFXEntityConverter

register_converter(IFXEntityConverter, 'ifx_entity')

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="/he/")),
    url(r'', include("users.oauth_urls")),
]

urlpatterns += i18n_patterns(
    url(r'', include("movies.urls")),
    url(r'^people/', include("people.urls")),
    url(r'^search/', include("search.urls")),
    url(r'^collections/', include("curation.urls")),
    url(r'^links/', include("links.urls")),

    url(r'^enrich/', include("enrich.urls")),

    url(r'^logs/', include("editing_logs.urls")),
    url(r'^reports/', include("reports.urls")),
    url(r'^vendor/', include("vendor_data.urls")),

    url(r'', include("users.urls")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
)

vendor_data/urls.py
from django.urls import path

from . import views

app_name = "vendor_data"

urlpatterns = [
    path("", views.VendorListView.as_view(), name='list'),
    path("all/", views.VendorDataListView.as_view(), name='item_list'),
    path("<int:pk>/", views.VendorDataListView.as_view(),
         name='vendor_item_list'),
    path("item/<int:pk>/set/movie/<int:entity_id>/",
         views.SetVendorItemEntityView.as_view(), name='set-movie'),
]

vendor_data/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import JSONField
from django.db import models, transaction
from django.db.models import Count
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from general.entities import ENTITY_CONTENT_TYPES
from links.tasks import add_links


class VendorManager(models.Manager):
    def get_by_natural_key(self, key):
        return self.get(key=key)


class Vendor(models.Model):
    key = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    pid = models.CharField(max_length=50, unique=True, null=True, blank=True)
    template = models.CharField(max_length=500, null=True, blank=True)

    objects = VendorManager()

    def __str__(self):
        return self.key

    def natural_key(self):
        return (self.key,)

    def get_absolute_url(self):
        return reverse("vendor_data:vendor_item_list", args=(self.pk,))


class VendorGenre(models.Model):
    # property: https://www.wikidata.org/wiki/Property:P136
    # film genre: https://www.wikidata.org/wiki/Q201658
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT,
                               related_name="genre")
    value = models.CharField(max_length=250)
    qid = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        unique_together = (
            ('vendor', 'value'),
        )

    def __str__(self):
        return f"{self.vendor}: {self.value}"


class VendorItemQuerySet(models.QuerySet):
    def stats(self):
        qs = self.values('status').order_by('status').annotate(
            count=Count('status'))

        return [{
            'key': d['status'],
            'label': VendorItem.Status.to_label[d['status']],
            'value': d['count'],
            'badge': VendorItem.Status.badges[d['status']],
        } for d in qs]

    def with_wikidata_id(self):
        return self.exclude(wikidata_id=None)


class VendorItem(models.Model):
    class Type:
        MOVIE = 1
        PERSON = 2
        choices = (
            (MOVIE, _("movie")),
            (PERSON, _("person")),
        )

    class Status:
        NEW = 1
        TO_BE_CREATED = 5
        ASSIGNED = 10
        NOT_APPLICABLE = 999

        choices = (
            (NEW, _('New')),
            (TO_BE_CREATED, _('Pending creation of a new Wikidata ID')),
            (ASSIGNED, _('Assigned')),
            (NOT_APPLICABLE, _('N/A')),
        )

        to_label = dict(choices)

        badges = {
            NEW: 'danger',
            TO_BE_CREATED: 'warning',
            ASSIGNED: 'success',
            NOT_APPLICABLE: 'info',
        }

    created_at = models.DateTimeField(_('created at'), auto_now_add=True,
                                      db_index=True)

    status = models.PositiveIntegerField(choices=Status.choices,
                                         default=Status.NEW)

    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT,
                               related_name="items")
    vid = models.CharField(_('vendor_id'), max_length=400)

    type = models.IntegerField(choices=Type.choices)

    wikidata_id = models.CharField(max_length=50, null=True, blank=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.PROTECT,
                                     limit_choices_to=ENTITY_CONTENT_TYPES,
                                     null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    entity = GenericForeignKey()

    year = models.IntegerField(_("year"), null=True, blank=True)
    duration = models.IntegerField(_("duration"), null=True, blank=True)
    title_he = models.CharField(_('Hebrew title'), max_length=300, null=True,
                                blank=True)
    title_en = models.CharField(_('English title'), max_length=300, null=True,
                                blank=True)
    summary_he = models.TextField(_('summary in Hebrew'), null=True,
                                  blank=True)
    summary_en = models.TextField(_('summary in English'), null=True,
                                  blank=True)
    editing_comment = models.TextField(_('editing comment'), null=True,
                                       blank=True)
    imdb_id = models.CharField(('imdb ID'), max_length=50, null=True,
                               blank=True)

    extra_data = JSONField(null=True, blank=True)

    genre = models.ManyToManyField(VendorGenre, related_name="items",
                                   blank=True)

    objects = VendorItemQuerySet.as_manager()

    class Meta:
        unique_together = (
            ('vendor', 'vid'),
        )
        ordering = (
            '-created_at',
        )

    def __str__(self):
        return f"{self.get_type_display()}: {self.vendor.key}.{self.vid}"

    def url(self):
        if self.vendor.template:
            return self.vendor.template.replace("$1", self.vid)
        return self.vid

    def get_better_status_display(self):
        if self.entity:
            return _("Linked") if self.entity.wikidata_id else _("Unlinked")
        return self.get_status_display()

    def set_wikidata_id(self, id):
        assert self.entity.wikidata_id is None or self.entity.wikidata_id == id, self.entity
        with transaction.atomic():
            self.wikidata_id = id
            self.save()
            self.entity.wikidata_status = self.entity.Status.ASSIGNED
            self.entity.wikidata_id = id
            self.entity.save()
        add_links(self.entity)

vendor_data/views.py
import difflib
import logging
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from typing import Iterable

from general.templatetags.ifx import ut_plus
from ifx.base_views import DataContributorOnlyMixin
from movies.models import Movie
from reports.views import BaseReport
from . import models

logger = logging.getLogger(__name__)


class VendorListView(DataContributorOnlyMixin, ListView):
    model = models.Vendor
    all_items = models.VendorItem.objects.all()


def get_titles():
    q = Q(title_he__isnull=False) | Q(title_en__isnull=False)
    for m in Movie.objects.filter(q):  # type: Movie
        if m.title_he:
            assert m.title_he
            yield m.title_he
        if m.title_en:
            assert m.title_en
            yield m.title_en


def get_my_close_matches(words, possibilities, cutoff=0.75):
    if not 0.0 <= cutoff <= 1.0:
        raise ValueError("cutoff must be in [0.0, 1.0]: %r" % (cutoff,))

    s = difflib.SequenceMatcher()
    for word in words:
        s.set_seq2(word)
        for x in possibilities:
            s.set_seq1(x)
            if s.real_quick_ratio() >= cutoff and s.quick_ratio() >= cutoff:
                n = s.ratio()
                if n >= cutoff:
                    yield n, x


def find_candidates(titles, v):
    words = filter(None, (v.title_he, v.title_en))
    near = sorted(get_my_close_matches(words, titles), reverse=True)[:8]
    return [
        (n, t, Movie.objects.active().filter(Q(title_he=t) | Q(title_en=t)))
        for
        n, t in near]


def add_candidates(qs: Iterable[models.VendorItem]):
    titles = sorted(set(get_titles()))

    for v in qs:
        if not v.entity:
            v.candidates = find_candidates(titles, v)
        yield v


class VendorDataListView(BaseReport):
    breadcrumbs = (
        (_("Vendors"), reverse_lazy("vendor_data:list")),
    )

    template_name = "vendor_data/vendordata_list.html"

    COLS = (
        _("Vendor"),
        _("Vendor ID"),
        # _("Type"),
        _("Status"),
        _("Hebrew Title"),
        _("English Title"),
        _("Year"),
        _("Duration"),
        _("IMDB"),
        _("Entity / Candidates"),
    )
    model = models.VendorItem

    def get_breadcrumbs(self):
        return super().get_breadcrumbs()

    def limit_to_vendor(self):
        return 'pk' in self.kwargs

    def get_title(self):
        if self.limit_to_vendor():
            return self.vendor.title
        return super().get_title()

    def get_queryset(self):
        qs = super().get_queryset()
        if self.limit_to_vendor():
            self.vendor = get_object_or_404(models.Vendor,
                                            pk=self.kwargs['pk'])
            qs = qs.filter(vendor=self.vendor)
        return list(add_candidates(qs))

    def cols(self):
        start = 1 if self.limit_to_vendor() else 0
        return self.COLS[start:]


class SetVendorItemEntityView(DataContributorOnlyMixin, SingleObjectMixin,
                              View):
    model = models.VendorItem

    def post(self, request, *args, **kwargs):
        o = self.get_object()  # type: models.VendorItem
        en = get_object_or_404(Movie, pk=kwargs['entity_id'])

        if o.entity is None:
            o.entity = en
            o.status = o.Status.ASSIGNED
            o.save()
        return JsonResponse({'html': ut_plus(o.entity)})

vendor_data/templates/vendor_data/vendor_list.html
{% extends 'base.html' %}
{% load static i18n humanize ifx %}

{% block content %}

    <ul class="list-group">
        <li class="list-group-item">
            <a href="{% url "vendor_data:item_list" %}">
                {% trans "All" %}
            </a>
            ({{ view.all_items.count|intcomma }})
            {% for stat in view.all_items.stats %}
                <span class="badge badge-{{ stat.badge }}">{{ stat.label }}: {{ stat.value|intcomma }}</span>
            {% endfor %}
        </li>
        {% for object in object_list %}
            <li class="list-group-item">
                {{ object|u:'title' }}
                ({{ object.items.count|intcomma }})
                {% for stat in object.items.stats %}
                    <span class="badge badge-{{ stat.badge }}">{{ stat.label }}: {{ stat.value|intcomma }}</span>
                {% endfor %}
                <span class="badge badge-info">With wikidata ID: {{ object.items.with_wikidata_id.count|intcomma }}</span>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

vendor_data/templates/vendor_data/vendordata_list.html
{% extends "base_datatable.html" %}
{% load staticfiles i18n humanize bootstrap4 ifx movies %}

{% block container_class%}container-fluid{% endblock %}

{% block row %}
    <tr>
        {% if not view.vendor %}
            <td>{{ object.vendor.title }}</td>
        {% endif %}
        <td data-search="{{ object.vid }}"><a
                href="{{ object.url }}">{{ object.vid }}</a></td>
        {#        <td>{{ object.get_type_display }}</td>#}
        <td>{{ object.get_better_status_display }}</td>
        <td>{{ object.title_he }}</td>
        <td>{{ object.title_en|default:'' }}</td>
        <td>{{ object.year|default:'' }}</td>
        <td>
            {% if object.duration %}
                {{ object.duration|duration }}
            {% endif %}
        </td>
        <td>
            {% if object.imdb_id %}
                <a href="https://www.imdb.com/title/{{ object.imdb_id }}/">
                    <span class="fab fa-imdb"></span>
                </a>
            {% endif %}
        </td>
        <td>
            {% if object.entity %}
                {{ object.entity|ut_plus }}
                {% if object.entity.wikidata_id %}
                    <a href="{{ object.entity.wikidata_url }}"
                       title="{{ object.entity.wikidata_id }}"><span
                            class="fa fa-barcode"></span></a>
                {% endif %}
                {% if object.entity.year %}
                    ({{ object.entity.year }})
                {% endif %}
                {% if object.entity.duration %}
                    <span class="badge badge-light p-0"><span
                            class="fa fa-clock"></span> {{ object.entity.duration|duration }} </span>

                {% endif %}
            {% else %}
                <ul class="list-unstyled">
                    {% for score, title, items in object.candidates %}
                        <li>
                            {{ score|floatformat:3 }}: {{ title }}
                            <br/>
                            {% for item in items %}
                                <span class="badge badge-{% if score >= 0.9 %}success{% elif score >= 0.8 %}info{% else %}warning{% endif %}">
                                    {{ item|ut_plus }}
                                    {% if item.year %}
                                        ({{ item.year }})
                                    {% endif %}
                                    {% if item.wikidata_id %}
                                        {% include "_wikidata_icon.html" with o=item %}
                                    {% endif %}
                                    &nbsp;
                                    <span data-url="{% url "vendor_data:set-movie" object.id item.id %}"
                                          class="set-movie active fa fa-save"></span>
                                </span>

                            {% endfor %}
                        </li>
                    {% endfor %}
                </ul>

            {% endif %}
        </td>
        {#        {% for g in v.genre.all %}#}
        {#            <span class="badge badge-pill badge-primary">{{ g.value }}</span>#}
        {#        {% endfor %}#}
    </tr>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static "js/csrf.js" %}"></script>
    <script src="{% static "js/report_utils.js" %}"></script>
    <script src="{% static "js/vendoritem_list.js" %}"></script>
{% endblock %}