enrich/urls.py
from django.conf.urls import url

from . import views

app_name = "enrich"

urlpatterns = [
    url(r"^$", views.SuggestionListView.as_view(), name='list'),
    url(r"^(?P<pk>\d+)/refresh/$", views.SuggestionForceLookupView.as_view(),
        name='refresh'),
    url(r"^(?P<pk>\d+)/set-wikidata-id/$", views.SetWikiDataIDView.as_view(),
        name='set_wd_id'),
]

ifx/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import register_converter
from django.views.generic import RedirectView

from ifx.converters import IFXEntityConverter

register_converter(IFXEntityConverter, 'ifx_entity')

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="/he/")),
    url(r'', include("users.oauth_urls")),
]

urlpatterns += i18n_patterns(
    url(r'', include("movies.urls")),
    url(r'^people/', include("people.urls")),
    url(r'^search/', include("search.urls")),
    url(r'^collections/', include("curation.urls")),
    url(r'^links/', include("links.urls")),

    url(r'^enrich/', include("enrich.urls")),

    url(r'^logs/', include("editing_logs.urls")),
    url(r'^reports/', include("reports.urls")),
    url(r'^vendor/', include("vendor_data.urls")),

    url(r'', include("users.urls")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
)

movies/urls.py
from django.conf.urls import url

import general.views
from . import views

app_name = "movies"
urlpatterns = [

    url(r"^$", general.views.HomePage.as_view(), name='home'),

    url(r"^about/$", general.views.AboutView.as_view(), name='about'),

    url(r"^movie/$", views.MovieListView.as_view(), name='list'),
    url(r"^movie/(?P<pk>[0-9]+)/$", views.MovieDetailView.as_view(),
        name='detail'),
    url(r"^movie/(?P<pk>[0-9]+)/edit/$", views.MovieUpdateView.as_view(),
        name='edit'),
    url(r"^movie/(?P<pk>[0-9]+)/upload/$", views.PostMovieToWikiDataView.as_view(),
        name='upload'),

    url(r"^movie/(?P<pk>[0-9]+)/merge-into/(?P<other>[0-9]+)$",
        views.MergeIntoView.as_view(),
        name='merge'),

    url(r"^field/$", views.FieldListView.as_view(), name='field_list'),
    url(r"^field/(?P<pk>[0-9]+)/$", views.FieldDetailView.as_view(),
        name='field_detail'),
    url(r"^tag/(?P<pk>[0-9]+)/$", views.TagDetailView.as_view(),
        name='tag_detail'),

]

people/urls.py
from django.urls import path

from . import views

app_name = "people"

urlpatterns = [
    path("", views.PersonListView.as_view(), name='list'),
    path("<int:pk>/", views.PersonDetailView.as_view(), name='detail'),
    path("<int:pk>/edit/", views.PersonUpdateView.as_view(), name='edit'),
    path("<int:pk>/upload/", views.PostPersonToWikiDataView.as_view(),
         name='upload'),

    path("<int:pk>/merge-into/<int:other>/", views.MergeIntoView.as_view(),
         name='merge'),
]

users/urls.py
from django.urls import path

from . import views

app_name = "user_profiles"

urlpatterns = [
    path("my-profile/",
         views.MyProfileView.as_view(), name='my_profile'),
]

general/views.py
from pathlib import Path

import markdown
from django.conf import settings
from django.utils import translation
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView

from ifx.base_views import IFXMixin
from movies.models import Movie
from people.models import Person


class HomePage(IFXMixin, TemplateView):
    template_name = 'home.html'
    jumbotron = 'movies/main_jumbotron.html'
    title = _("Home")

    def random_movies(self, n=3):
        return Movie.objects.active().order_by("?")[:n]

    def random_people(self, n=8):
        return Person.objects.active().exclude(movies=None).order_by("?")[:n]


class AboutView(IFXMixin, TemplateView):
    template_name = "movies/about.html"
    jumbotron = "movies/about_jumbotron.html"
    title = _("About")

    def get_html_content(self):
        lang = translation.get_language()[:2]
        with (Path(settings.BASE_DIR) / f"about_{lang}.md").open() as f:
            return mark_safe(markdown.markdown(f.read()))

general/templates/_footer.html
{% load i18n static %}

<div class="bg-white pb-2">
    <div class="container">
        <div class="alert alert-warning">
            <div class="row">
                <div class="col-sm-9">
                    <div class="lead mt-2">
                        <b>{% trans "This website is in active development and may contain errors and inaccuracies" %}</b>
                    </div>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-warning btn-block btn-lg"
                       href="{% url "movies:about" %}">{% trans "More information" %}</a>
                </div>
            </div>
        </div>
    </div>
</div>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-5">
                <ul class="list-unstyled">
                    <li><a href="{% url "movies:about" %}">{% trans "About" %}</a></li>
                    <li><a href="{% url "movies:about" %}">{% trans "Contact Us" %}</a></li>
                    <li><a href="{% url "movies:about" %}">{% trans "License Terms" %}</a></li>
                </ul>

            </div>
            <div class="offset-lg-1 col-lg-3 col-md-5">
                <a title="{% trans "Jerusalem Cinematheque" %}"
                   href="https://www.jer-cin.org.il/he/lobby/%D7%90%D7%A8%D7%9B%D7%99%D7%95%D7%9F-%D7%99%D7%A9%D7%A8%D7%90%D7%9C%D7%99-%D7%9C%D7%A1%D7%A8%D7%98%D7%99%D7%9D/">
                    <img class="footer-logo img-fluid"
                         src="{% static "images/Jerusalem_Cinematheque_LogoBlack.png" %}"

                         alt="{% trans "Jerusalem Cinematheque" %}"/>
                </a>
            </div>
            <div class="offset-lg-2 col-lg-3 col-md-4 text-left">
                <a title="{% trans "OpenGLAM Accelerator" %}"
                        href="https://oglam.hasadna.org.il/">
                    <img class="footer-logo img-fluid"
                         src="{% static "images/openglam-logo.png" %}"
                         alt="{% trans "Jerusalem Cinematheque" %}"/>
                </a>
            </div>
            <div class="col-lg-1 col-md-1 pl-2 pr-2">
                <a title="{% trans "Open Knowledge Workshop" %}"
                   href="http://www.hasadna.org.il/">
                    <img class="footer-logo img-fluid"
                         src="{% static "images/hasadna-logo.png" %}"
                         alt="{% trans "Jerusalem Cinematheque" %}"/>
                </a>
            </div>
        </div>
    </div>
</footer>

general/templates/_header.html
{% load i18n ifx staticfiles %}
{% get_current_language as LANGUAGE_CODE %}
<header>
    <div class="header">
        <!--button class="btnMenu"><img src="/static/images/Menu.svg"/></button-->
        <div class="pos-f-t">
            <div class="side-nav collapse" id="navbarToggleExternalContent">
                <div class="bg-inverse p-4">
                    <div class="list-group">
                        <a href="{% url 'movies:list' %}"
                           class="list-group-item list-group-item-action">{% trans "Movies" %}</a>
                        <a href="{% url 'people:list' %}"
                           class="list-group-item list-group-item-action">{% trans "Personalities" %}</a>
                        <a href="{% url 'movies:field_list' %}"
                           class="list-group-item list-group-item-action">{% trans "Fields" %}</a>
                        <a href="{% url 'movies:about' %}"
                           class="list-group-item list-group-item-action">{% trans "About Archive" %}</a>
                        {#                        <a href="#"#}
                        {#                           class="list-group-item list-group-item-action">{% trans "Conservation and Restoration" %}</a>#}
                        {#                        <a href="#"#}
                        {#                           class="list-group-item list-group-item-action">{% trans "Depositing Materials" %}</a>#}
                        {#                        <a href="#"#}
                        {#                           class="list-group-item list-group-item-action">{% trans "Contact" %}</a>#}
                        {#                        <a href="#"#}
                        {#                           class="list-group-item list-group-item-action">{% trans "Jerusalem Cinematheque Site" %}</a>#}
                        {% if user.is_editor %}
                            <a href="{% url 'curation:list' %}"
                               class="list-group-item list-group-item-action">{% trans "Collections" %}</a>
                            <a href="{% url "enrich:list" %}"
                               class="list-group-item list-group-item-action">
                                {% trans "Edit Suggestions" %}
                            </a>
                            <a href="{% url "reports:list" %}"
                               class="list-group-item list-group-item-action">
                                {% trans "Reports" %}
                            </a>
                            <a href="{% url "editing_logs:list" %}"
                               class="list-group-item list-group-item-action">
                                {% trans "Editing Logs" %}
                            </a>
                        {% endif %}
                        {% if user.is_staff %}
                            <a href="{% url "admin:index" %}"
                               class="list-group-item list-group-item-action">{% trans "Admin" %}</a>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <a href="{% url "user_profiles:my_profile" %}"
                               class="list-group-item list-group-item-action">
                            <span class="fa fa-user"></span>
                                {{ user }}
                            </a>
                            <a href="{% url "logout" %}"
                               class="list-group-item list-group-item-action">{% trans "Logout" %}</a>
                        {% else %}
                            <a href="{% url "login" %}"
                               class="list-group-item list-group-item-action">
                                <span class="fa fa-user"></span>
                                {% trans "Login" %}
                            </a>
                        {% endif %}
                    </div>

                </div>
            </div>
            <nav class="navbar-inverse bg-inverse">
                <button class="navbar-toggler btnMenu" type="button"
                        data-toggle="collapse"
                        data-target="#navbarToggleExternalContent"
                        aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <img src="{% static "images/Menu.svg" %}"/>
                </button>
            </nav>
        </div>
        <a class="lang-switcher pull-right"
           href="{{ request.path|switch_lang }}">{% if LANGUAGE_CODE == 'he' %}
            ENG{% else %}עבר{% endif %}</a>
        <div class="logo">
            <a href="{% url "movies:home" %}">{% trans "Israeli Film Archive Catalog" %}</a>
        </div>

        <form id="searchform" action="{% url 'movies:list' %}">
            {% csrf_token %}
            <div id="searchBarUp">
                <div>
                    <input type="text" class="upperSearchInput sInput"
                           name="title"
                           placeholder="{% trans 'Search...' %}">
                </div>
                <div>
                    <button class="searchIcon"
                            type="submit"><span class="fa fa-search"></span>
                    </button>
                </div>
            </div>
        </form>

    </div>

    {% if view.jumbotron %}
        {% include view.jumbotron %}
    {% endif %}

</header>

general/templates/_idea_bid.html
{% load i18n %}
{% if object.idea_bid %}
    <div class="card bg-dark mb-1">
        <div class="card-body">
            <p class="card-text text-light">
                {% trans "Legacy ID" %}: {{ object.idea_bid }}
                {% if object.idea_modified %}
                    | <b class="text-danger">{% trans "Modified" %}</b>
                {% endif %}
            </p>
        </div>
    </div>
{% endif %}

general/templates/_pagination.html
{% load i18n ifx humanize %}

{% if page_obj and page_obj.paginator.num_pages > 1 %}
    <div class="pagination row m-1">
        <div class="col-12 col-md-6 text-center">
            {% trans "Page" %}
            {{ page_obj.number|intcomma }}
            {% trans "of" %}
            {{ page_obj.paginator.num_pages|intcomma }}

            <i>
                ({% trans "Items" %} #{{ page_obj.start_index|intcomma }} - #{{ page_obj.end_index|intcomma }})
            </i>
        </div>

        <div class="col-6 col-md-3 order-md-first">
            {% if page_obj.has_previous %}
                <a class="btn btn-sm btn-light" href="?{% qs page=1 %}">
                    &laquo; {% trans "first" %}
                </a>
                <a class="btn btn-sm btn-light" href="?{% qs page=page_obj.previous_page_number %}">
                    &lsaquo; {% trans "previous" %}
                </a>
            {% endif %}
        </div>
        <div class="col-6 col-md-3 text-right">
            {% if page_obj.has_next %}
                <a class="btn btn-sm btn-light" href="?{% qs page=page_obj.next_page_number %}">
                    {% trans "next" %} &rsaquo;
                </a>
                <a class="btn btn-sm btn-light" href="?{% qs page=page_obj.paginator.num_pages %}">
                    {% trans "last" %} &raquo;
                </a>
            {% endif %}
        </div>
    </div>
{% endif %}

general/templates/_wikidata_icon.html
{% load staticfiles %}
{% if o.wikidata_id %}
    <img src="{% static "images/wikidata-logo.svg" %}" height="20"
         alt="{{ o.wikidata_id }}" class="pb-1">
{% endif %}

general/templates/generic_form.html
{% extends 'base.html' %}
{% load static i18n humanize bootstrap4 ifx %}

{% block content %}

    <form method="post" novalidate>
        {% csrf_token %}

        {% bootstrap_form form %}

        <button class="btn btn-primary">
            <span class="fa fa-save"></span>
            {% if object %}
                {% trans "Save" %}
            {% else %}
                {% trans "Add" %}
            {% endif %}
        </button>
    </form>

{% endblock %}

general/templates/home.html
{% extends 'base.html' %}
{% load static i18n ifx %}

{% block header_container %}
{% endblock %}

{% block content %}
    <div class="row">

        <div class="col-md-8">
            <h3 class="p-2">
                {% trans "Movies" %}
            </h3>
            {% include "movies/_movies.html" with object_list=view.random_movies hide_totals=1 %}
            <div class="text-right">
                <a href="{% url "movies:list" %}" class="btn btn-light btn-lg">
                    {% trans "All Movies" %} &raquo;
                </a>
            </div>
        </div>

        <div class="col-md-4">
            <h3 class="pb-2 pt-2">
                {% trans "People" %}
            </h3>
            <ul class="list-group">
                {% for object in view.random_people %}
                    <li class="list-group-item">
                        {{ object|ut_plus }}
                        <span dir="ltr">({{ object.movies.count }})</span>

                        {% for mrp in object.distinct_roles %}
                            <span class="badge badge-light">{{ mrp.role|bdtitle }}</span>
                        {% endfor %}
                    </li>
                {% endfor %}
            </ul>
            <div class="text-right">
                <a href="{% url "people:list" %}" class="btn btn-light btn-lg">
                    {% trans "All People" %} &raquo;
                </a>
            </div>
        </div>
    </div>
{% endblock %}