curation/urls.py
from django.conf.urls import url

from . import views

app_name = "curation"

urlpatterns = [
    url(r"^$", views.CollectionListView.as_view(), name='list'),
    url(r"^add/$", views.CollectionCreateView.as_view(), name='create'),
    url(r"^(?P<pk>[0-9]+)/$", views.CollectionDetailView.as_view(),
        name='detail'),
]

ifx/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import register_converter
from django.views.generic import RedirectView

from ifx.converters import IFXEntityConverter

register_converter(IFXEntityConverter, 'ifx_entity')

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="/he/")),
    url(r'', include("users.oauth_urls")),
]

urlpatterns += i18n_patterns(
    url(r'', include("movies.urls")),
    url(r'^people/', include("people.urls")),
    url(r'^search/', include("search.urls")),
    url(r'^collections/', include("curation.urls")),
    url(r'^links/', include("links.urls")),

    url(r'^enrich/', include("enrich.urls")),

    url(r'^logs/', include("editing_logs.urls")),
    url(r'^reports/', include("reports.urls")),
    url(r'^vendor/', include("vendor_data.urls")),

    url(r'', include("users.urls")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
)

movies/urls.py
from django.conf.urls import url

import general.views
from . import views

app_name = "movies"
urlpatterns = [

    url(r"^$", general.views.HomePage.as_view(), name='home'),

    url(r"^about/$", general.views.AboutView.as_view(), name='about'),

    url(r"^movie/$", views.MovieListView.as_view(), name='list'),
    url(r"^movie/(?P<pk>[0-9]+)/$", views.MovieDetailView.as_view(),
        name='detail'),
    url(r"^movie/(?P<pk>[0-9]+)/edit/$", views.MovieUpdateView.as_view(),
        name='edit'),
    url(r"^movie/(?P<pk>[0-9]+)/upload/$", views.PostMovieToWikiDataView.as_view(),
        name='upload'),

    url(r"^movie/(?P<pk>[0-9]+)/merge-into/(?P<other>[0-9]+)$",
        views.MergeIntoView.as_view(),
        name='merge'),

    url(r"^field/$", views.FieldListView.as_view(), name='field_list'),
    url(r"^field/(?P<pk>[0-9]+)/$", views.FieldDetailView.as_view(),
        name='field_detail'),
    url(r"^tag/(?P<pk>[0-9]+)/$", views.TagDetailView.as_view(),
        name='tag_detail'),

]

people/urls.py
from django.urls import path

from . import views

app_name = "people"

urlpatterns = [
    path("", views.PersonListView.as_view(), name='list'),
    path("<int:pk>/", views.PersonDetailView.as_view(), name='detail'),
    path("<int:pk>/edit/", views.PersonUpdateView.as_view(), name='edit'),
    path("<int:pk>/upload/", views.PostPersonToWikiDataView.as_view(),
         name='upload'),

    path("<int:pk>/merge-into/<int:other>/", views.MergeIntoView.as_view(),
         name='merge'),
]

search/urls.py
from django.conf.urls import url

from . import views

app_name = "search"
urlpatterns = [
    url(r"^$", views.MoviesSearchListView.as_view(), name='query'),

    # #url(r"^searchresult/$", views.MoviesSearchListView.as_view(), name='searchresult'),
    # url(r"^$", search.views.searchresult, name='searchresult'),
    # url(r"^by-year/$", views.search_by_year, name='search_by_year'),
]

movies/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from ifx.forms import PostToWikiDataForm
from .models import Movie

MOVIE_FIELDS = (
    'year',
    'duration',
    'title_he',
    'title_en',
)

MERGE_FIELDS = MOVIE_FIELDS + (
    'summary_he',
    'summary_en',
)


class MovieForm(forms.ModelForm):
    editing_comment = forms.CharField(label=_('Editing Comment'),
                                      widget=forms.Textarea)

    class Meta:
        model = Movie
        fields = MOVIE_FIELDS


class SearchByYearForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = [
            'year',
        ]


class PostMovieToWikiDataForm(PostToWikiDataForm):
    title_he = forms.BooleanField(label=_("Hebrew title"), required=False,
                                  initial=True)
    title_en = forms.BooleanField(label=_("English title"), required=False,
                                  initial=True)
    year = forms.BooleanField(label=_("year"), required=False, initial=True)
    duration = forms.BooleanField(label=_("duration"), required=False,
                                  initial=True)

movies/views.py
import django_filters
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db.models import Count, Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView, UpdateView, FormView
from django.views.generic.detail import BaseDetailView
from django_filters.views import FilterView

from editing_logs.api import Recorder
from general.templatetags.ifx import bdtitle
from ifx.base_filters import WikidataEntityFilter
from ifx.base_views import IFXMixin, EntityActionMixin, \
    DataContributorOnlyMixin, PostToWikiDataView
from movies import forms
from movies.models import Movie, Tag, Field
from wikidata_edit.upload import upload_movie


def get_tags():
    return ((t.id, f"{bdtitle(t)} ({t.movie_count})") for t in
            Field.objects.get(idea_fid='AJAN').tags.annotate(
                movie_count=Count('movies')).order_by('title_he'))


class MovieFilter(WikidataEntityFilter):
    title = django_filters.CharFilter(method='title_filter', label=_("title"))
    year = django_filters.RangeFilter()
    duration = django_filters.RangeFilter()
    tags__tag = django_filters.ChoiceFilter(choices=get_tags, label=_("Genre"))
    summary = django_filters.CharFilter(method='summary_filter',
                                        label=_("summary"))

    ordering = django_filters.OrderingFilter(

        label=_("ordering"),
        fields=(
            ('title_he', 'title_he'),
            ('title_en', 'title_en'),
            ('year', 'year'),
            ('duration', 'duration'),
        ),

        field_labels={
            'title_he': _('Hebrew Title (A -> Z)'),
            'title_en': _('English Title (A -> Z)'),
            'year': _('Year (Old -> New)'),
            'duration': _('Duration (Short -> long)'),
            '-title_he': _('Hebrew title (Z -> A)'),
            '-title_en': _('English title (Z -> A)'),
            '-year': _('Year (New -> Old)'),
            '-duration': _('Duration (Long -> Short)'),
        }
    )

    class Meta:
        model = Movie
        fields = (
            'title',
            'year',
            'duration',
            'tags__tag',
        )

    def title_filter(self, queryset, name, value):
        q = Q(title_en__icontains=value) | Q(title_he__icontains=value)
        return queryset.filter(q)

    def summary_filter(self, queryset, name, value):
        q = Q(summary_en__icontains=value) | Q(summary_he__icontains=value)
        return queryset.filter(q)


class MovieListView(IFXMixin, FilterView):
    filterset_class = MovieFilter
    template_name = "movies/movie_list.html"
    model = Movie
    paginate_by = 25
    ordering = "title_he"
    queryset = Movie.objects.active()


class MovieDetailView(IFXMixin, DetailView):
    model = Movie

    breadcrumbs = (
        (_("Movies"), reverse_lazy("movies:list")),
    )

    def predispatch(self):
        if not self.get_object().active and not self.request.user.is_editor():
            raise PermissionDenied()
        super().predispatch()

    def possible_duplicates(self):
        q = Q()
        if self.object.title_he:
            q |= Q(title_he=self.object.title_he)
        if self.object.title_en:
            q |= Q(title_en=self.object.title_en)
        if not q:
            return None
        return Movie.objects.filter(q, active=True).exclude(id=self.object.id)


class MovieUpdateView(DataContributorOnlyMixin, UpdateView):
    model = Movie
    breadcrumbs = MovieDetailView.breadcrumbs
    form_class = forms.MovieForm


class PostMovieToWikiDataView(PostToWikiDataView):
    form_class = forms.PostMovieToWikiDataForm
    model = Movie
    breadcrumbs = MovieDetailView.breadcrumbs
    action_name = _("Upload to WikiData")
    fields = forms.MOVIE_FIELDS
    link_type_key = 'for_movies'

    def get_initial(self):
        o = self.get_object()  # type: Movie
        d = super().get_initial()
        d['desc_en'] = f"{o.year} Israeli film" if o.year else "Israeli film"
        d['desc_he'] = f"סרט ישראלי משנת {o.year}" if o.year else "סרט ישראלי"
        for lt in self.get_link_types():
            vi = o.vendor_items.filter(vendor__pid=lt.wikidata_id).first()
            if vi:
                k = f'ext_{lt.wikidata_id}'
                d[k] = vi.vid

        return d

    def upload(self, d, ids, o):
        labels = {}
        if d['title_he']:
            labels['he'] = o.title_he
        if d['title_en']:
            labels['en'] = o.title_en
        descs = {}
        if d['desc_he']:
            descs['he'] = d['desc_he']
        if d['desc_en']:
            descs['en'] = d['desc_en']
        duration = o.duration if d['duration'] else None
        year = o.year if d['year'] else None
        resp = upload_movie(self.request.user.get_wikidata_oauth1(),
                            labels, descs, ids, year,
                            duration)
        return resp


class MergeIntoView(EntityActionMixin, BaseDetailView, FormView):
    model = Movie
    breadcrumbs = MovieDetailView.breadcrumbs
    action_name = _("Merge into another movie")
    form_class = forms.forms.Form
    template_name = "movies/movie_merge.html"

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.other = get_object_or_404(Movie, pk=self.kwargs['other'])
        return super().dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        o = self.object  # type: Movie
        if o.wikidata_id and not self.other.wikidata_id:
            form.fields['wikidata_id'] = forms.forms.BooleanField(
                required=False, initial=True,
                label=_("WikiData ID"))

        for fld in forms.MERGE_FIELDS:
            v = getattr(o, fld)
            old = getattr(self.other, fld)
            if v and v != old:
                form.fields[fld] = forms.forms.BooleanField(
                    required=False, help_text=v, initial=not old,
                    label=o._meta.get_field(fld).verbose_name)

        for t in o.tags.all():
            k = f"t_{t.id}"
            form.fields[k] = forms.forms.BooleanField(
                required=False, initial=True,
                label=f"{bdtitle(t.tag.field)} > {bdtitle(t.tag)}")

        for r in o.people.all():
            k = f"r_{r.id}"
            form.fields[k] = forms.forms.BooleanField(
                required=False, initial=True,
                label=f"{bdtitle(r.role)} > {bdtitle(r.person)}")

        return form

    def form_valid(self, form):
        o = self.object  # type: Movie
        d = form.cleaned_data

        with Recorder(user=self.request.user, note="merge") as r:
            r.record_update_before(o)

            if o.wikidata_id and not self.other.wikidata_id and d[
                'wikidata_id']:
                self.other.wikidata_id = o.wikidata_id
                o.wikidata_id = None
                self.other.wikidata_status = o.wikidata_status
                o.wikidata_status = o.Status.NOT_APPLICABLE

            o.active = False
            o.merged_into = self.other
            o.save()
            r.record_update_after(o)
            o.suggestions.all().delete()

            for fld in forms.MERGE_FIELDS:
                v = getattr(o, fld)
                old = getattr(self.other, fld)
                if v and v != old and d[fld]:
                    setattr(self.other, fld, v)
                    self.other.idea_modified = True

            r.record_update_before(o.__class__.objects.get(pk=self.other.pk))
            self.other.save()
            r.record_update_after(self.other)

            for t in o.tags.all():
                k = f"t_{t.id}"
                if d[k]:
                    tag, created = self.other.tags.get_or_create(tag=t.tag)
                    if created:
                        r.record_addition(tag)

            for ro in o.people.all():
                k = f"r_{ro.id}"
                if d[k]:
                    mrp, created = self.other.people.get_or_create(
                        role=ro.role, person=ro.person,
                        defaults={'priority': ro.priority, 'note': ro.note}
                    )
                    if created:
                        r.record_addition(mrp)
                if ro.active:
                    r.record_update_before(ro)
                    ro.active = False
                    ro.save()
                    r.record_update_after(ro)

            for l in o.links.all():
                r.record_update_before(l)
                l.entity = self.other
                l.save()
                r.record_update_after(l)

            for vi in o.vendor_items.all():
                vi.entity = self.other
                vi.save()

        messages.success(self.request, _("Merged."))

        return redirect(o)


class FieldListView(IFXMixin, ListView):
    model = Field

    def get_queryset(self):
        return Field.objects.annotate(
            movie_count=Count('tags__movies')).filter(
            movie_count__gt=0)


class FieldDetailView(IFXMixin, DetailView):
    breadcrumbs = (
        (_("Fields"), reverse_lazy("movies:field_list")),
    )

    model = Field


TAG_ORDER_FIELDS = {
    'title_he',
    'title_en',
    'lang',
    'type_id',
}


class TagDetailView(IFXMixin, DetailView):
    model = Tag

    def get_breadcrumbs(self):
        fld = self.get_object().field
        return FieldDetailView.breadcrumbs + (
            (str(fld), fld.get_absolute_url()),
        )

search/views.py
import re

from django.db.models import Q

from movies.views import MovieListView

YEAR_RANGE_RE = re.compile(r"^(?P<start>(19|20)[0-9][0-9])-(?P<end>(19|20)[0-9][0-9])$")


class MoviesSearchListView(MovieListView):
    def get_queryset(self):
        qs = super(MoviesSearchListView, self).get_queryset()
        query = self.request.GET.get('q')
        search_type = self.request.GET.get('idselect')
        q = self.get_filters(query, search_type)
        qs = qs.filter(q)
        return qs

    def get_filters(self, query, search_type):
        q = (
                Q(title_he__icontains=query) |
                Q(title_en__icontains=query) |
                Q(summary_he__icontains=query) |
                Q(summary_en__icontains=query)
        )
        if query.isdigit():
            q |= Q(year=int(query))
        m = YEAR_RANGE_RE.match(query)
        if m:
            q |= Q(year__gte=m['start'], year__lte=m['start'])

        return q

movies/templates/movies/_collection.html
{% load i18n static %}

<div class="container row">
    <div class="container-image">
        <div class="collection-class">
            <h4 class="text">Collection Name</h4>
        </div>
      <img src="{% static 'images/defaultImg.jpg' %}" alt="Avatar" class="image">
      <div class="overlay">
        <div class="text"><button class="btnRegular">{% trans "Watch Collection" %}</button></div>
      </div>
    </div>
</div>

movies/templates/movies/_comment.html
{% load humanize %}
<li>
    <b>[#{{ c.id }}]
        <span title="{{ c.created_at }}">{{ c.created_at|naturaltime }}</span>
    </b>:
    {{ c.content|linebreaks }}
</li>

movies/templates/movies/_header1.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<header>
    <div class="App-header">
        <!--button class="btnMenu"><img src="/static/images/Menu.svg"/></button-->
        <div class="pos-f-t">
            <div class="side-nav collapse" id="navbarToggleExternalContent">
                <div class="bg-inverse p-4">
                    <div class="list-group">
                        <a href="{% url 'movies:list' %}"
                           class="list-group-item list-group-item-action">{% trans "Movies" %}</a>
                        <a href="{% url 'people:list' %}"
                           class="list-group-item list-group-item-action">{% trans "Personalities" %}</a>
                        <a href="{% url 'curation:list' %}"
                           class="list-group-item list-group-item-action">{% trans "Collections" %}</a>
                        <a href="{% url 'movies:field_list' %}"
                           class="list-group-item list-group-item-action">{% trans "Fields" %}</a>
                        <a href="{% url 'movies:about' %}"
                           class="list-group-item list-group-item-action">{% trans "About Archive" %}</a>
{#                        <a href="#"#}
{#                           class="list-group-item list-group-item-action">{% trans "Conservation and Restoration" %}</a>#}
{#                        <a href="#"#}
{#                           class="list-group-item list-group-item-action">{% trans "Depositing Materials" %}</a>#}
{#                        <a href="#"#}
{#                           class="list-group-item list-group-item-action">{% trans "Contact" %}</a>#}
{#                        <a href="#"#}
{#                           class="list-group-item list-group-item-action">{% trans "Jerusalem Cinematheque Site" %}</a>#}
                        {% if user.is_authenticated %}
                            <a href="#"
                               class="list-group-item list-group-item-action">{{ user }}</a>
                            <a href="{% url "logout" %}"
                               class="list-group-item list-group-item-action">{% trans "Logout" %}</a>
                        {% else %}
                            <a href="{% url "login" %}"
                               class="list-group-item list-group-item-action">{% trans "Login" %}</a>
                        {% endif %}
                    </div>

                </div>
            </div>
            <nav class="navbar-inverse bg-inverse">
                <button class="navbar-toggler btnMenu" type="button"
                        data-toggle="collapse"
                        data-target="#navbarToggleExternalContent"
                        aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <img src="/static/images/Menu.svg"/>
                </button>
            </nav>
        </div>
        <div class="logo">
            <a href="{% url 'movies:home' %}#"><img
                    src="/static/images/Jerusalem_Cinematheque_Logo.png"
                    alt="Jerusalem Cinematheque Logo"></a>
            <span>{% trans "Israeli Film <br> Arcive" %}</span>
        </div>

        <form id="lang-form" action="{% url 'set_language' %}"
              method="post">{% csrf_token %}
            <input id="redirectLang" name="next" type="hidden"
                   value="{{ redirect_to }}"/>
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}

            <input type="hidden" name="language"
                   value="{% if LANGUAGE_CODE == 'he' %}en-us{% else %}he{% endif %}">
            <input id="lang-switcher" type="submit" class="langHebEng" value="{% if LANGUAGE_CODE == 'he' %}English⏵{% else %}⏴עברית{% endif %}"/>
        </form>
{#        <a class="btnBag" href="#"><img src="/static/images/Shopping-bag.svg"/></a>#}
        <a id="searchShowHide" class="btnSearchIcon glyphicon glyphicon-search"
           href="#"></a>

        <form id="searchform" action="{% url 'search:query' %}">
            {% csrf_token %}
            <div id="searchBarUp">
                <div>
                    <input type="text" class="upperSearchInput sInput" name="q"
                           placeholder="{% trans 'Search...' %}">
                </div>
                <div>
                    <button class="searchIcon"
                            type="submit"><span class="fa fa-search"></span> </button>
                </div>
            </div>
        </form>

    </div>

    {% block header %}
        {% if view.jumbotron %}
            {% include view.jumbotron %}
        {% endif %}
    {% endblock %}

</header>

movies/templates/movies/collections_list.html
<h1>My Collections</h1>

<ul>
    <a href= {% url "movies:collection_create" %}>Add collection...</a>
</ul>

<table border="1" width="100%">
    <tr>
        <th>#</th>
        <th>Title</th>
    </tr>
    {% for object in objects %}
        <tr>
            <td>#{{ object.id }}</td>
            <td>
                <a href={% url "movies:collection_detail" object.id %}>{{ object.title }}</a>
            </td>
        </tr>
    {% endfor %}

</table>

movies/templates/movies/detail.html
<h1>Movie #{{ movie.bid }}</h1>

<ul>
    <li><b>{{ movie.title }}</b></li>
    <li>Year: {{ movie.year }}</li>
    <li>Language: {{ movie.lang }}  </li>

    <li>bid: {{movie.bid}} </li>
    <li>Additional data:<ul>
        {% for key,values in movie.get_extra_data.items %}
        <li>
            <b>{{key}}:</b>
            {% for value in values %}
                <q>{{ value }}</q>
            {% endfor %}
        </li>
        {% endfor %}
    </ul>
    </li>
</ul>

<a href="{% url "movies:list" %}">Back To My Movies</a>

movies/templates/movies/field_detail.html
{% extends 'base.html' %}
{% load static i18n ifx %}

{% block content %}

    <ul class="list-group">
        {% for tag in object.get_tags|bdorder %}
            <li class="list-group-item">
                {{ tag|ut }}
                <span dir="ltr">({{ tag.count }})</span>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

movies/templates/movies/form.html
<form method="post" novalidate>
    {% csrf_token %}

    {{ form.as_ul }}

    <button>Add</button>
</form>

movies/templates/movies/movie_details.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <div class="container">
        <h1 id="h1reasult"><strong>{% trans "Title" %} {{ movie.get_pretty_title }}</strong> ({{ movie.year }})</h1>
        <form action="">
                <input class="addToChart" type="image" src="{% static 'images/Shopping-bag-black.svg' %}" alt="Submit">
        </form>

        <div class="movieDetails">
            <div class="row">
                <div class="col-6">
                    <h5>{% trans "Runtime" %}: <span>{{ object.duration }} {% trans "min" %}</span></h5>
                    <h5>{% trans "Director" %}: <span>{}</span></h5>
                    <h5>{% trans "Producer" %}: <span>{}</span></h5>
                    <h5>{% trans "Screenwriter" %}: <span>{}</span></h5>
                    <h5>{% trans "Photographer" %}: <span>{}</span></h5>
                    <h5>{% trans "Cast" %}: <span>{}</span></h5>
                    <h5>{% trans "Genre/s" %}: <span>{}</span></h5>
                    <h5>{% trans "Color" %}: <span>{}</span></h5>
                </div>
                <div class="col-6">
                    <img src="" />
                </div>
            </div>

            <hr>
            <section>
                <h5>{% trans "Summery" %}:</h5>
                <p>
                    {{value}}
                </p>
            </section>

        </div>
    </div>
{% endblock %}

movies/templates/movies/movie_form.html
{% extends 'base.html' %}
{% load static i18n humanize bootstrap4 ifx %}

{% block content %}

    <form method="post" novalidate>
        {% csrf_token %}

        {% bootstrap_form form %}

        <button class="btn btn-primary">
            <span class="fa fa-save"></span>
            {% if object %}
                {% trans "Save" %}
            {% else %}
                {% trans "Add" %}
            {% endif %}
        </button>
    </form>

{% endblock %}

movies/templates/movies/movie_merge.html
{% extends 'base.html' %}
{% load static i18n humanize bootstrap4 ifx %}

{% block content %}

    <form method="post" novalidate>
        {% csrf_token %}

        {% bootstrap_form form %}

        <button class="btn btn-primary">
            <span class="fa fa-code-branch"></span>
            {% trans "Merge" %}
        </button>
    </form>

{% endblock %}

movies/templates/movies/search_form.html
<form method="post" validate>
    {% csrf_token %}

    {{ form.as_ul }}

    <button>Search</button>
</form>

movies/templates/movies/search_result.html
{% extends 'base.html' %}
{% load static i18n %}
{% csrf_token %}

{% block content %}
    <div class="container">
        <h1 id="h1reasult">{% trans "Search results for:" %} {{query}}</h1>

        <ul>Count: {{count}} items</ul>
        <table border="1" width="100%">
            <tr>
                <th>#</th>
                <th>idea_bid</th>
                <th>Title</th>
                <th>Year</th>
                <th>Language</th>
            </tr>
            {% for object in objects %}
                <tr>
                    <td>#{{ object.id }}</td>
                    <td>{{ object.idea_bid }}</td>
                    <td>
                        <a href= "{% url 'movies:detail' object.id %}">{{ object.get_pretty_title }}</a>
                    </td>
                    <td>{{ object.year }}</td>
                    <td>{{ object.lang }} </td>
                </tr>
            {% endfor %}

        </table>
    </div>
{% endblock %}

movies/templates/movies/searchresult.html
{% extends 'base.html' %}
{% load static i18n %}
{% csrf_token %}

{% block content %}
    <h1 id="h1reasult">{% trans "Search reasults for" %}: {{ query }}</h1>
    <div class="row justify-content-between">
        <div class="col-6">
            <span>{{ count }} {% trans "Titles were found" %}</span>
        </div>

        <div class="col-6 sortBy">
            <span>{% trans "Sorted by" %}:</span>
            <select class="dropdown dropBtnSearchUp sortDropdown"
                    aria-labelledby="dropdownMenu1">
                <option value="1"><a href="#">{% trans "Title A-Z" %}</a>
                </option>
                <span role="separator" class="divider"></span>
                <option value="2"><a href="#">{% trans "Oldest" %}</a></option>
                <span role="separator" class="divider"></span>
                <option value="3"><a href="#">{% trans "Newest" %}</a></option>
                <span role="separator" class="divider"></span>
                <option value="4"><a href="#">{% trans "Director A-Z" %}</a>
                </option>
            </select>
        </div>

    </div>

    <hr>
    <ul class="list-group">

        {% for object in object_list %}
            {% include 'movies/_movies.html' %}
        {% endfor %}
    </ul>
{% endblock %}

movies/templates/movies/tag_detail.html
{% extends 'base.html' %}
{% load static i18n ifx %}

{% block content %}
    <ul>
        {% if object.title_he %}
            <li><b>{% trans "Hebrew Title" %}:</b> {{ object.title_he }}</li>
        {% endif %}

        {% if object.title_en %}
            <li><b>{% trans "English Title" %}:</b> {{ object.title_en }}</li>
        {% endif %}

    </ul>
    {{ object.active_movies.count }} {% trans "Movies" %}
    <ul class="list-group">
        {% for item in object.active_movies %}
            <li class="list-group-item">
                <a href="{% url 'movies:detail' item.movie.id %}">
                    {{ item.movie.get_title }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}