editing_logs/urls.py
from django.conf.urls import url

from movies.models import Movie
from people.models import Person
from . import views

app_name = "editing_logs"

urlpatterns = [
    url(r"^$", views.LogItemListView.as_view(), name='list'),
    url(r"^movie/(?P<pk>[0-9]+)/$", views.EntityLogItemListView.as_view(),
        kwargs={'model': Movie},
        name='movie'),
    url(r"^person/(?P<pk>[0-9]+)/$", views.EntityLogItemListView.as_view(),
        kwargs={'model': Person},
        name='person'),
]

ifx/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import register_converter
from django.views.generic import RedirectView

from ifx.converters import IFXEntityConverter

register_converter(IFXEntityConverter, 'ifx_entity')

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="/he/")),
    url(r'', include("users.oauth_urls")),
]

urlpatterns += i18n_patterns(
    url(r'', include("movies.urls")),
    url(r'^people/', include("people.urls")),
    url(r'^search/', include("search.urls")),
    url(r'^collections/', include("curation.urls")),
    url(r'^links/', include("links.urls")),

    url(r'^enrich/', include("enrich.urls")),

    url(r'^logs/', include("editing_logs.urls")),
    url(r'^reports/', include("reports.urls")),
    url(r'^vendor/', include("vendor_data.urls")),

    url(r'', include("users.urls")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
)

people/urls.py
from django.urls import path

from . import views

app_name = "people"

urlpatterns = [
    path("", views.PersonListView.as_view(), name='list'),
    path("<int:pk>/", views.PersonDetailView.as_view(), name='detail'),
    path("<int:pk>/edit/", views.PersonUpdateView.as_view(), name='edit'),
    path("<int:pk>/upload/", views.PostPersonToWikiDataView.as_view(),
         name='upload'),

    path("<int:pk>/merge-into/<int:other>/", views.MergeIntoView.as_view(),
         name='merge'),
]

people/models.py
from collections import defaultdict

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from enrich.wikidata import HUMAN
from ifx.base_models import Undeletable, WikiDataEntity
from movies.models import Movie


class Person(Undeletable, WikiDataEntity):
    ENTITY_CODE = 'person'
    WIKIDATA_CLASSIFIER_PID = HUMAN

    name_he = models.CharField(_('Hebrew name'), max_length=300, null=True,
                               blank=True, db_index=True)
    name_en = models.CharField(_('English name'), max_length=300, null=True,
                               blank=True, db_index=True)
    first_name_he = models.CharField(max_length=300, null=True, blank=True,
                                     db_index=True)
    first_name_en = models.CharField(max_length=300, null=True, blank=True,
                                     db_index=True)
    last_name_he = models.CharField(max_length=300, null=True, blank=True,
                                    db_index=True)
    last_name_en = models.CharField(max_length=300, null=True, blank=True,
                                    db_index=True)
    idea_tid = models.IntegerField(unique=True, null=True, blank=True)
    idea_modified = models.BooleanField(default=False)
    merged_into = models.ForeignKey('self', null=True, blank=True,
                                    on_delete=models.PROTECT)

    links = GenericRelation('links.Link')
    suggestions = GenericRelation('enrich.Suggestion')

    FIELDS_TO_LOG = (
        'name_he',
        'name_en',
        'first_name_he',
        'first_name_en',
        'last_name_he',
        'last_name_en',
        'idea_tid',
        'idea_modified',
        'wikidata_status',
        'wikidata_id',
        'merged_into_id',
    )

    class Meta:
        verbose_name = _("person")
        verbose_name_plural = _("people")

    def __str__(self):
        return str(self.name_en or self.name_he)

    def get_absolute_url(self):
        return reverse('people:detail', args=(self.pk,))

    def distinct_roles(self):
        return self.movies.distinct('role')

    def movies_flat(self):
        movies = defaultdict(set)
        for mrp in self.movies.active().filter(movie__active=True).order_by(
                '-movie__year'):
            movies[mrp.movie].add(mrp.role)

        for m, roles in movies.items():
            m.roles = roles
            yield m

    @property
    def title_he(self):
        return self.name_he

    @property
    def title_en(self):
        return self.name_en


class Role(Undeletable, WikiDataEntity):
    title_en = models.CharField(max_length=300, null=True, blank=True)
    title_he = models.CharField(max_length=300, null=True, blank=True)
    priority = models.PositiveIntegerField(default=100)
    appears_in_short_version = models.BooleanField(default=False)
    short_version_order = models.PositiveIntegerField(null=True, blank=True)
    idea_tid = models.CharField(unique=True, max_length=300, null=True,
                                blank=True)
    idea_modified = models.BooleanField(default=False)

    FIELDS_TO_LOG = (
        'title_en',
        'title_he',
        'priority',
        'appears_in_short_version',
        'short_version_order',
        'idea_tid',
        'idea_modified',
    )

    class Meta:
        verbose_name = _("role")
        verbose_name_plural = _("roles")

    def __str__(self):
        return self.title_en or self.title_he or "???"


class MovieRolePerson(Undeletable):
    movie = models.ForeignKey(Movie, related_name='people',
                              on_delete=models.PROTECT)
    role = models.ForeignKey(Role, related_name='movie_people',
                             on_delete=models.PROTECT)
    person = models.ForeignKey(Person, related_name='movies',
                               on_delete=models.PROTECT)
    priority = models.PositiveIntegerField(default=100)
    note = models.CharField(max_length=250, null=True, blank=True)
    idea_uid = models.IntegerField(null=True, blank=True, unique=True)
    idea_modified = models.BooleanField(default=False)

    FIELDS_TO_LOG = (
        'movie_id',
        'role_id',
        'person_id',
        'priority',
        'note',
        'idea_uid',
        'idea_modified',
    )

    class Meta:
        unique_together = (
            ('movie', 'role', 'person'),
        )

    @property
    def title_he(self):
        return self.role.title_he

    @property
    def title_en(self):
        return self.role.title_en

people/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from ifx.forms import PostToWikiDataForm
from .models import Person

PERSON_FIELDS = (
    'name_he',
    'name_en',
)

MERGE_FIELDS = PERSON_FIELDS + (
    'first_name_he',
    'first_name_en',
    'last_name_he',
    'last_name_en',
)


class PersonForm(forms.ModelForm):
    editing_comment = forms.CharField(label=_('Editing Comment'),
                                      widget=forms.Textarea)

    class Meta:
        model = Person
        fields = PERSON_FIELDS


GENDER_CHOICES = (
    (None, '---------'),
    (6581097, _("Male")),
    (6581072, _("Female")),
    (1097630, _("Intersex")),
    (1052281, _("Transgender Female")),
    (2449503, _("Transgender Male")),
)


class PostPersonToWikiDataForm(PostToWikiDataForm):
    name_he = forms.BooleanField(label=_("Hebrew name"), required=False,
                                  initial=True)
    name_en = forms.BooleanField(label=_("English name"), required=False,
                                  initial=True)
    gender = forms.TypedChoiceField(choices=GENDER_CHOICES,
                                    coerce=int,
                                    empty_value=None,
                                    label=_("gender"), required=False)

people/views.py
import django_filters
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db.models import Q, Count
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, UpdateView, FormView
from django.views.generic.detail import BaseDetailView
from django_filters.views import FilterView

from editing_logs.api import Recorder
from general.templatetags.ifx import bdtitle
from ifx.base_filters import WikidataEntityFilter
from ifx.base_views import IFXMixin, EntityEditMixin, EntityActionMixin, \
    PostToWikiDataView
from people.models import Person, Role
from wikidata_edit.upload import upload_person
from . import forms


def get_roles():
    return ((t.id, bdtitle(t)) for t in Role.objects.order_by('title_he'))


class PersonFilter(WikidataEntityFilter):
    name = django_filters.CharFilter(method='name_filter', label=_("name"))
    movies__role = django_filters.ChoiceFilter(choices=get_roles,
                                               label=_("role"))

    ordering = django_filters.OrderingFilter(
        label=_("ordering"),
        fields=(
            ('name_he', 'name_he'),
            ('name_en', 'name_en'),
            ('role_count', 'role_count'),
        ),

        field_labels={
            'name_he': _('Hebrew Name (A -> Z)'),
            '-name_he': _('Hebrew name (Z -> A)'),
            'name_en': _('English Name (A -> Z)'),
            '-name_en': _('English name (Z -> A)'),
            '-role_count': _('Number of roles (Descending)'),
            'role_count': _('Number of roles (Ascending)'),
        }
    )

    class Meta:
        model = Person
        fields = (
            'name',
            'movies__role',
        )

    def name_filter(self, queryset, name, value):
        q = Q(name_en__icontains=value) | Q(name_he__icontains=value)
        return queryset.filter(q)


class PersonListView(IFXMixin, FilterView):
    template_name = "people/person_list.html"
    filterset_class = PersonFilter
    model = Person
    queryset = Person.objects.annotate(role_count=Count('movies'))
    paginate_by = 50

    def get_queryset(self):
        return super().get_queryset().active().filter(
            movies__isnull=False).distinct()

    def get_ordering(self):
        k = self.request.GET.get('order', None)
        if k not in PERSON_ORDER_FIELDS:
            k = "name_he"
        return k


class PersonDetailView(IFXMixin, DetailView):
    model = Person

    breadcrumbs = (
        (_("People"), reverse_lazy("people:list")),
    )

    def predispatch(self):
        if not self.get_object().active and not self.request.user.is_editor():
            raise PermissionDenied()
        super().predispatch()

    def possible_duplicates(self):
        q = Q()
        if self.object.name_he:
            q |= Q(name_he=self.object.name_he)
        if self.object.name_en:
            q |= Q(name_en=self.object.name_en)
        if not q:
            return None
        return self.model.objects.filter(q, active=True).exclude(
            id=self.object.id)


PERSON_ORDER_FIELDS = {
    'name_he',
    'name_en',
    'first_name_he',
    'first_name_en',
    'last_name_he',
    'last_name_en',
}


class PersonUpdateView(EntityEditMixin, UpdateView):
    model = Person
    breadcrumbs = PersonDetailView.breadcrumbs
    form_class = forms.PersonForm
    template_name = "generic_form.html"


class MergeIntoView(EntityActionMixin, BaseDetailView, FormView):
    model = Person
    breadcrumbs = PersonDetailView.breadcrumbs
    action_name = _("Merge into another person")
    form_class = forms.forms.Form
    template_name = "movies/movie_merge.html"

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.other = get_object_or_404(Person, pk=self.kwargs['other'])
        return super().dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        o = self.object  # type: Person
        if o.wikidata_id and not self.other.wikidata_id:
            form.fields['wikidata_id'] = forms.forms.BooleanField(
                required=False, initial=True,
                label=_("WikiData ID"))

        for fld in forms.MERGE_FIELDS:
            v = getattr(o, fld)
            old = getattr(self.other, fld)
            if v and v != old:
                form.fields[fld] = forms.forms.BooleanField(
                    required=False, help_text=v, initial=not old,
                    label=o._meta.get_field(fld).verbose_name)

        for r in o.movies.all():
            k = f"r_{r.id}"
            form.fields[k] = forms.forms.BooleanField(
                required=False, initial=True,
                label=f"{bdtitle(r.role)} > {bdtitle(r.movie)}")

        return form

    def form_valid(self, form):
        o = self.object  # type: Person
        d = form.cleaned_data

        with Recorder(user=self.request.user, note="merge") as r:
            r.record_update_before(o)

            if o.wikidata_id and not self.other.wikidata_id and d[
                'wikidata_id']:
                self.other.wikidata_id = o.wikidata_id
                o.wikidata_id = None
                self.other.wikidata_status = o.wikidata_status
                o.wikidata_status = o.Status.NOT_APPLICABLE

            o.active = False
            o.merged_into = self.other
            o.save()
            r.record_update_after(o)
            o.suggestions.all().delete()

            for fld in forms.MERGE_FIELDS:
                v = getattr(o, fld)
                old = getattr(self.other, fld)
                if v and v != old and d[fld]:
                    setattr(self.other, fld, v)
                    self.other.idea_modified = True

            r.record_update_before(o.__class__.objects.get(pk=self.other.pk))
            self.other.save()
            r.record_update_after(self.other)

            for ro in o.movies.all():
                k = f"r_{ro.id}"
                if d[k]:
                    mrp, created = self.other.movies.get_or_create(
                        role=ro.role, movie=ro.movie,
                        defaults={'priority': ro.priority, 'note': ro.note}
                    )
                    if created:
                        r.record_addition(mrp)
                if ro.active:
                    r.record_update_before(ro)
                    ro.active = False
                    ro.save()
                    r.record_update_after(ro)

            for l in o.links.all():
                r.record_update_before(l)
                l.entity = self.other
                l.save()
                r.record_update_after(l)

        messages.success(self.request, _("Merged."))

        return redirect(o)


class PostPersonToWikiDataView(PostToWikiDataView):
    form_class = forms.PostPersonToWikiDataForm
    model = Person
    breadcrumbs = PersonDetailView.breadcrumbs
    action_name = _("Upload to WikiData")
    fields = forms.PERSON_FIELDS
    link_type_key = 'for_people'

    # def get_initial(self):
    #     o = self.get_object()
    #     d = super().get_initial()
    #     d['desc_en'] = f"{o.year} Israeli film" if o.year else "Israeli film"
    #     d['desc_he'] = f"סרט ישראלי משנת {o.year}" if o.year else "סרט ישראלי"
    #     return d

    def upload(self, d, ids, o):
        labels = {}
        if d['name_he']:
            labels['he'] = o.name_he
        if d['name_en']:
            labels['en'] = o.name_en
        descs = {}
        if d['desc_he']:
            descs['he'] = d['desc_he']
        if d['desc_en']:
            descs['en'] = d['desc_en']
        resp = upload_person(self.request.user.get_wikidata_oauth1(),
                             labels, descs, ids, d['gender'])
        return resp

people/templates/people/person_detail.html
{% extends 'base.html' %}
{% load static i18n ifx %}

{% block header_container %}
    <h1>
        <div class="row flex-rtl">
            <div class="col-6 rtl">
                {% if object.name_he %}
                    <b>{{ object.name_he }}</b>
                {% endif %}
            </div>
            <div class="col-6 ltr">
                {% if object.name_en %}
                    <b>{{ object.name_en }}</b>
                {% endif %}
            </div>
        </div>
    </h1>
    {% if not object.active %}
        <p class="display-1 bg-danger text-center">
            {% trans "INACTIVE" %}
        </p>
        {% if object.merged_into %}
            <p class="display-3 bg-danger text-center">
                {% trans "Merged into" %}
                {{ object.merged_into|ut_plus }}
            </p>
        {% endif %}
    {% endif %}
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-sm-8">
            {% include "movies/_movies.html" with object_list=object.movies_flat count=object.movies.count %}
        </div>

        <div class="col-sm-4">

            {% include "enrich/_suggestions.html" %}

            {% include "links/_links.html" with create_url="links:create_person" edit_url="links:update_person" %}

            <div class="card bg-warning mb-2">
                <div class="card-header">
                    {% trans "Search the web" %}
                </div>
                <ul class="list-group list-group-flush">
                    {% if object.name_he %}
                        <li class="list-group-item">
                            {% trans "Hebrew Title" %}
                            {% search_links object.name_he 'he' %}
                        </li>
                    {% endif %}

                    {% if object.name_en %}
                        <li class="list-group-item">
                            {% trans "English Title" %}:
                            {% search_links object.name_en 'en' %}
                        </li>
                    {% endif %}
                </ul>
            </div>

            {% if user.is_editor %}

                {% if not object.wikidata_id %}
                    <div class="card mb-2">
                        <h4 class="card-header">
                            <a href="{% url "people:upload" object.id %}">
                                <span class="fa fa-upload"></span> {% trans "Upload to WikiData" %}
                            </a>
                        </h4>
                    </div>
                {% endif %}

                {% if object.idea_tid %}
                    <div class="card bg-dark mb-1">
                        <div class="card-body">
                            <p class="card-text text-light">
                                {% trans "Legacy ID" %}: {{ object.idea_tid }}
                                {% if object.idea_modified %}
                                    |
                                    <b class="text-danger">{% trans "Modified" %}</b>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                {% endif %}

                <div class="card bg-success mb-1">
                    <div class="card-body">
                        <p class="card-text text-light">
                            <a class="text-light"
                               href="{% url "people:edit" object.id %}">
                                <span class="fa fa-edit"></span> {% trans "Edit" %}
                            </a>
                            |
                            <a class="text-light"
                               href="{% url "editing_logs:person" object.id %}">
                                <span class="fa fa-list"></span> {% trans "Logs" %}
                            </a>
                        </p>
                    </div>
                </div>

                {% if view.possible_duplicates.count %}

                    <div class="card bg-warning mb-1">
                        <div class="card-header">
                            {% trans "Possible Duplicates" %}
                        </div>
                        <ul class="list-group">
                            {% for p in view.possible_duplicates %}
                                <a href="{{ p.get_absolute_url }}"
                                   class="list-group-item  list-group-item-action">
                                    <span class="badge badge-primary">#{{ p.id }}</span>
                                    {{ p|bdtitle_plus }}
                                </a>
                                <a href="{% url "people:merge" object.id p.id %}"
                                   class="list-group-item  list-group-item-action">
                                    <span class="fa fa-code-branch"></span> {% trans "Merge" %}
                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

            {% endif %}

        </div>
    </div>

{% endblock %}

people/templates/people/person_list.html
{% extends 'base.html' %}
{% load static i18n humanize ifx bootstrap4 %}

{% block content %}

    <div class="row">
        <div class="col-sm-3 col-md-2 col-lg-2">
            <h5 class="totals">
                {% trans "Filter" %}
            </h5>

            <form>
                {% bootstrap_form filter.form %}
                <button class="btn btn-primary">{% trans "Filter" %}</button>
            </form>
        </div>
        <div class="col-sm-9 col-md-10 col-lg-10">

            <h5 class="totals">
                {% if paginator.count == 0 %}
                    {% trans "No items found" %}
                {% elif paginator.count == 1 %}
                    {% trans "One item found" %}
                {% else %}
                    {% trans "Found" %}
                    {{ paginator.count |intcomma }}
                    {% trans "items" %}
                {% endif %}
            </h5>

            {% pagination page_obj %}

            <ul class="list-group">
                {% for object in object_list %}
                    <li class="list-group-item">
                        {{ object|ut_plus }}
                        {% wikidata_icon object %}

                        <span dir="ltr">({{ object.movies.count }})</span>

                        ({% for mrp in object.distinct_roles %}
                        {{ mrp.role|bdtitle }}{% if not forloop.last %},
                        {% endif %}{% endfor %})

                    </li>
                {% endfor %}
            </ul>

            {% pagination page_obj %}
        </div>
    </div>

{% endblock %}